Common values arrays and Binary Search
MrCasco/ideen-test-inator pull request #49
Opened 2021-11-21 21:32 UTC by sanchezpili6

## PR Description

Problemas de Valores en común entre dos arreglos y binary search. 
También cambié el color de fondo de los problemas. 

### Screen Shots/Recordings

![image](https://user-images.githubusercontent.com/37568592/142779681-bfa359ef-1ce6-4929-b8f0-9e2768463dbf.png)

### Related Issues/Tickets

2021-11-21 21:45 UTC, MrCasco commented on testing/respuestas.js
> +    'respuestas': diccionarioArgumentosRespuestas([[[3, 4, 6, 1], [2, 4, 1, 5]], [[4, 6, 23, 67, 2], [2, 6, 1, 98, 23]], [[56, 34, 5, 1], [4, 1, 4, 6, 5]], [[2, 3, 6, 12, 1], [2, 3, 6, 12, 1]]], [[4,
Puedes poner aquí la nueva función? Ya está mergeado en master

2021-11-21 21:46 UTC, MrCasco commented on testing/textosProblemas/textos.js
> +      " Input = [4, 6, 7, 2, 1], [3, 8, 5, 2, 9]  <- se recibe como dos arreglos de enteros\n"+
Puedes poner en el texto que ahora se va a recibir un arreglo con los dos arreglos adentro? Así:
function foo(args) {
  arg1 = args[0]
  arg2 = args[1]
}

2021-11-21 21:47 UTC, MrCasco requested changes
Falta cambiar el texto del problema para especificar que el input es un arreglo con 2 areglos dentro y utilizar la funcion nueva de multiuplesArgumentos

2021-11-22 13:38 UTC, JackieAnVal approved these changes
Excelente que ya funcione valoresEnComun <3

2021-11-22 13:39 UTC, merged